namespace Codout.Apis.Asaas.Models.MyAccount.Enums;

public enum AccountDocumentType
{
    ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT,
    CUSTOM,
    EMANCIPATION_OF_MINORS,
    ENTREPRENEUR_REQUIREMENT,
    IDENTIFICATION_SELFIE,
    IDENTIFICATION,
    INVOICE,
    MEI_CERTIFICATE,
    MINUTES_OF_CONSTITUTION,
    MINUTES_OF_ELECTION,
    POWER_OF_ATTORNEY,
    SOCIAL_CONTRACT
}
