namespace Codout.Apis.Asaas.Models.MyAccount.Enums;

public enum AccountDocumentResponsibleType
{
    ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT,
    ASAAS_ACCOUNT_OWNER_EMANCIPATION_AGE,
    ASAAS_ACCOUNT_OWNER,
    ASSOCIATION,
    BANK_ACCOUNT_OWNER_EMANCIPATION_AGE,
    BANK_ACCOUNT_OWNER,
    CUSTOM,
    DIRECTOR,
    INDIVIDUAL_COMPANY,
    LIMITED_COMPANY,
    MEI,
    PARTNER,
    POWER_OF_ATTORNEY
}
